spring:
  datasource:
    url: jdbc:mysql://smu-navi.cudr77napabi.ap-northeast-2.rds.amazonaws.com:3306/grishare
    driverClassName: com.mysql.cj.jdbc.Driver
    username: smunavi
    password: vi!^3na2~15
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    whitelabel:
      enabled: false